setting:
  name: "kitt_seq_00"
  output_root: "./experiments/"
  pc_path: "kitti/sequences/07/velodyne"
  pose_path: "kitti/poses/07.txt"
  calib_path: "kitti/sequences/07/calib.txt"
  load_model: False
  model_path: ""
  first_frame_ref: False
  begin_frame: 200
  end_frame: 250 # 1100
  every_frame: 1 # 1 means does not skip
  device: "cuda"
  gpu_id: "0"
  debug: False


process:
  min_range_m: 3.0
  pc_radius_m: 25.0  # TODO:
  min_z_m: -3.5
  rand_downsample: False # use random or voxel downsampling
  vox_down_m: 0.05
  rand_down_r: 0.2


sampler:
  surface_sample_range_m: 0.3
  surface_sample_n: 3
  free_sample_begin_ratio: 0.3
  free_sample_end_dist_m: 0.8
  free_sample_n: 3 # TODO currently, no free space

fea_encoding:
  type: 'fea_plane' # 'fea_octree' or 'fea_plane'
  use_features: True
  use_fixed_encoding: True
  progressive: False
  feature_dim: 8
  poly_int_on: False
  fea_octree:
    octree_fea_combine: 'add'
  fea_plane:
    regularization_loss_on: False
    record_feature_loss: False
    weight_r: 0.05
  fixed_encoding:
    fixed_enc_type: 'freq_nn' # 'freq' or 'ff' 'freq_nn'
    # for 'freq'
    n_bins: 16
    n_freq: 16
    # for 'ff'
    gaussian_scale: 50
    embedding_size: 16 # final: [3*embedding_size*2]
  octree:
    leaf_vox_size: 0.2
    tree_level_world: 12
    tree_level_feat: 3
    octree_from_surface_samples: True
  prior_estimation:
    opt_cor_sdf_only: False
    cor_sdf_w_feature: False
    coarse_compute: 'Nearest' # ['Average', 'Nearest', `NDT`, `Project`]


decoder:
  mlp_level: 2
  mlp_hidden_dim: 32 # TODO do I need to set higher?
  freeze_after_frame: 0


loss:
  ray_loss: False
  main_loss_type: sdf_bce  # select from sdf_bce (our proposed), sdf_l1, sdf_l2, dr, dr_neus
  sigma_sigmoid_m: 0.1
  loss_weight_on: False
  behind_dropoff_on: False
  ekional_loss_on: False
  weight_e: 0.1


continual:
  continual_learning_reg: False # using incremental mapping with regularization
  lambda_forget: 0
  window_replay_on: False # replay within the sliding window
  window_radius_m: 0


optimizer:
  iters: 20000
  batch_size: 8192
  learning_rate: 0.05
  weight_decay: 1e-7 # l2 regularization
  lr_decay_step: [20000, 50000, 100000]


eval:
  wandb_vis_on: False # log to wandb or not
  o3d_vis_on: False # visualize the mapping or not
  vis_freq_iters: 5000 # reconstruct the mesh every x iterations
  save_freq_iters: 5 # save the model and octree every x iterations
  mesh_freq_frame: 1
  mc_res_m: 0.1 # reconstruction marching cubes resolution
  mc_with_octree: True # querying sdf in the map bbx
  mc_vis_level: 1 # mask the voxels used for marching cubes reconstruction according to the octree level
  save_map: False # save the sdf map or not
